#!/usr/bin/env bash
# Install a nginx web server listening on port 80.
#
# Also, when querying nginx at its root / with a GET
# request, it returns a page that contains the string
# 'Hello World!'.
#

apt update
apt install -y nginx
ufw allow 'Nginx HTTP'
sed -i 's/80 default_server;/80;/g' /etc/nginx/sites-available/default
echo "Hello World!" > /var/www/html/index.html
service nginx restart