#!/usr/bin/env bash
#displays a list of currently running processes

current_date=$(date +"%b%d")
ps axo user,pid,%cpu,%mem,vsz,rss,tty,stat,lstart,time,command --forest | sed "1s/.*/& $current_date/"
