#!/usr/bin/env bash
#displays the time for 12 hours and 59 minutes:
#display hours from 0 to 12
#display minutes from 1 to 59

min=1
hour=0

echo "Hour: $hour"
while [[ "$min" -le 60 && "$hour" -le 12 ]] 
do
        if [ "$min" -eq 60 ]
        then
                hour=$(( hour +1))
                if [ "$hour" -lt 13 ] 
                then
                        echo "Hour: $hour"
                fi
                min=0
        else
                echo "$min"
        fi
        min=$(( min +1 ))
done
